config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #welcome route
  root "welcome#home", as: "home_page"

  #user route
  get "/users/:id" => "users#show", as: "user"

  #view posts shared by other user route
  get "/posts/shared_posts" => "posts#shared_posts", as: "shared_posts"

  get	"/posts/:id/edit(.:format)" =>	"posts#edit", as: "edit_posts_path"

  #user routes
  resources :users

  #post routes
  resources :posts

  resources :conversations, only: [:index, :show, :new, :create] do
   member do
     post :reply
     post :trash
     post :untrash
   end
 end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates_presence_of :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # acts_as_messageable

  def name
    return "You should add method :name in your Messageable model"
  end

  def mailboxer_email(object)
    #Check if an email should be sent for that object
    #if true
    return "define_email@on_your.model"
    #if false
    #return nil
  end

  #paperclip
  has_attached_file :avatar,
    :styles => { :medium => "300x300px>", :thumb => "100x100px>" },
    :default_url => "/assets/default-user-image copy.png"

  validates_attachment_content_type :avatar,
    :content_type => /\Aimage\/.*\Z/

  #associations
  has_many :posts


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #paperclip
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :user_name, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :user_name, :first_name, :last_name])
  end

  #devise
  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_filter :authenticate_user!
  helper_method :mailbox, :conversation

  def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(email: recipient_emails).all

    conversation = current_user.
      send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation_path(conversation)
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @user = User.find(current_user.id)
  end

  def create
    @new_post = Post.new(
      user_id: params[:post][:user_id].to_i,
      title: params[:post][:title],
      content: params[:post][:content],
      created_at: params[:post][:created_at],
    )
    @new_post.save

    if @new_post
      redirect_to url_for(:controller => :posts, :action => :index)
    else
      redirect_to url_for(:controller => :posts, :action => :new)
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_user = @post.user.first_name
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update({
      title: params[:post][:title],
      content: params[:post][:content],
      user_id: params[:post][:user_id],
      created_at: params[:post][:created_at]
      })

    if (@post)
      redirect_to url_for(:controller => :posts, :action => :index)
    else
      redirect_to url_for(:controller => :posts, :action => :edit)
    end
  end

  def destroy
    Post.delete(params[:id])
      redirect_to url_for(:controller => :posts, :action => :index)
  end

  def shared_posts
    # Post.find(params[:post_id]).user <<
    # User.find(params[:user_id])
  end

  private
  def post_params
    params.require(:post).permit(:user_id, :title, :content, :created_at)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
     @user = User.find(params[:id])
     @users = User.all
     @user_posts = @user.posts
     @post = Post.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
	   @message = "The Sharing App"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/mailboxer_helper.rb
module MailboxerHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SharingAppRails</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">

      <center>
        <nav>
          <% if (user_signed_in?) %>
            <%= link_to "Share", new_post_path %>
            <%= link_to "Users", users_path %>
            <%= link_to "Post Feed", posts_path %>
            <%= link_to "Inbox", shared_posts_path %>
            <%= link_to "Profile", user_path(current_user.id) %>
            <%= link_to 'Sign Out', { :action => 'destroy', :controller => 'devise/sessions' },	method: :delete %>
          <% else %>
            <%= link_to "Home", home_page_path %>
            <%= link_to 'Sign In', new_user_session_path %>
            <%= link_to 'Sign Up', new_user_registration_path %>
          <% end %>
        </nav>
      </center>

    </div>

    <br>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">

  <div class="row postedit">
    <div class="col-sm">
      <h1>
        Edit Your Post
      </h1>
    </div>
  </div>

  <div class="row postedit">
    <div class="col-sm">
      <h2>
        <%= form_for @post do |f| %>
          <%= f.label :title %>
          <br>
          <%= f.text_field :title %>
          <br>
          <%= f.label :content %>
          <br>
          <%= f.text_field :content %>
          <br>
          <%= f.hidden_field :created_at %>
          <%= f.label :user %>
          <br>
          <%= f.collection_select :user_id, User.all, :id, :first_name %>
          <br>
          <%= f.submit %>
        <% end %>
      </h2>
    </div>
  </div>

</div>

app/views/posts/index.html.erb
<div class="container">

  <div class="row postindex">
    <div class="col-sm">
      <h1>
        <%= link_to ("Share Something!"), new_post_path %>
      </h1>
      <br>
    </div>
  </div>

  <div class="row postindex">
    <div class="col-sm">
      <h1>
        <u>Post Feed</u>
      </h1>
    </div>
  </div>

  <div class="row postindex">
    <div class="col-sm">
      <h4>
        <% @posts.each do |post| %>
          <p>
            Title:
            <% post.id %>
            <%= post.title %>
          </p>
          <p>
            Content:
            <%= post.content %>
          </p>
          <p>
            Created At:
            <%= post.created_at %>
          </p>
          <%= link_to ("View Post"), post_path(post.id) %>
          <br>
          <%= link_to ("User's Profile"), user_path(post.id) %>
          <br>
          
          <%= link_to ("Edit Post"), edit_post_path(post.id) %>
          <br>
          <%= link_to 'Delete Post', { action: :destroy, id: post.id }, method: :delete %>
          <br>
          <hr>
        <% end %>
      </h4>
    </div>
  </div>

</div>

app/views/posts/new.html.erb
<div class="container">

  <div class="row postnew">
    <div class="col-sm">
      <h1>
        Create New Post
      </h1>
    </div>
  </div>

  <div class="row postnew">
    <div class="col-sm">
      <h2>
        <%= form_for Post.new do |f| %>
          <%= f.label :title %><br>
          <%= f.text_field :title %>
          <br>
          <%= f.label :content %><br>
          <%= f.text_field :content %>
          <br>
          <%= f.hidden_field :created_at %>
          <br>
          Send To <%= f.label :user %>:<br>
          <%= f.collection_select :user_id, User.all, :id, :user_name, prompt: :select %>
          <br>
          <%= f.submit %>
        <% end %>
      </h2>
    </div>
  </div>

</div>

app/views/posts/shared_posts.html.erb
<div class="container">

  <div class="row sharedposts">
    <div class="col-sm">
      <h1>
        My Inbox
      </h1>
    </div>
  </div>

</div>

app/views/posts/show.html.erb
<div class="container">

  <div class="row postshow">
    <div class="col-sm">
      <h2>
        <%= link_to ("Share Something!"), new_post_path %>
      </h2>
      <br>
    </div>
  </div>

  <div class="row postshow">
    <div class="col-sm">
      <h1>
        <%= @post.user.user_name %>'s Post
      </h1>
    </div>
  </div>

  <div class="row postshow">
    <div class="col-sm">
      <div>
        <% @post.id %>
        <h3>
          Title:
        </h3>
        <p>
          <%= @post.title %>
        </p>
        <h3>
          Content:
        </h3>
        <p>
          <%= @post.content %>
        </p>
        <h3>
          Created at:
        </h3>
        <p>
          <%= @post.created_at %>
        </p>
        <h3>
          Posted By:
        </h3>
        <p>
          <%= @post.user.first_name %> <%= @post.user.last_name %>
        </p>
        <hr>
        <%= link_to 'Delete Post', { action: :destroy, id: @post.id },
        method: :delete %> |
        <%= link_to 'Edit Post', edit_post_path(user_id: @post.id) %>
      </div>
    </div>
  </div>

</div>

app/views/users/index.html.erb
<div class="container">

  <div class="row userindex">
    <div class="col-sm">
      <h1>
        All Users
      </h1>
    </div>
  </div>

  <div class="row userindex">
    <div class="col-sm">
      <h4>
        <% @users.each do |user| %>
          <% user.id %>
          <%= link_to  user.user_name, user_path(user.id) %>
          <br>
          <%= image_tag user.avatar.url %>
          <br>
          <%= user.first_name %> <%= user.last_name %>
          <br>
          <a href="mailto:<%= user.email %>"><%= user.email %></a>
          <br>
          <!-- <%= link_to ("User's Profile page"), user_path(user.id) %> -->
          <!-- <br> -->
          <!-- <%= link_to 'Delete user',  { action: :destroy, id: user.id }, method: :delete %> -->
          <hr>
        <% end %>
      </h4>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container">

  <div class="row usershow">
    <div class="col-sm">
      <h1>
        All Users
      </h1>
      <h4>
        <% @users.each do |users| %>
        <%= link_to  users.user_name, user_path(users.id) %>
        <br>
        <% end %>
      </h4>
      <hr>
    </div>
  </div>

  <div class="row usershow">
    <div class="col-sm">
      <h1>
        My Profile
      </h1>
    </div>
  </div>

  <div class="row usershow">
    <div class="col-sm">
      <div>
        <!-- <%= @user.inspect %> -->
        <h4>
          <%= @user.user_name %>
        </h4>
        <h4>
          <%= @user.first_name %> <%= @user.last_name %>
        </h4>
        <h4>
          <%= @user.email %>
        </h4>
        <div>
          <%= image_tag @user.avatar.url %>
        </div>
      </div>
      <h4>
        <% if (user_signed_in?) %>
          <%= link_to "Edit Profile", edit_user_registration_path(user_id: @user.id) %>
        <% else %>
        <% end %>
      </h4>
      <br><br>
    </div>
  </div>

  <div class="row usershow">
    <div class="col-sm">
      <h4>
        My (<%= @user.user_name %>) Posts:
      </h4>
      <h4>
        <% @user_posts.each do |post| %>
        <% post.id %>
        <%= link_to (post.title), post_path(post.id) %>
        <br>
        <hr>
        <% end %>
      </h4>
    </div>
  </div>

</div>

app/views/welcome/home.html.erb
<center>
<h1>
  <%= @message %>
</h1>

<img src="/assets/SHARING_EXPERIENCE-512.png" alt="">
<br><br>
<h2>
  Family
</h2>
<br>
<h2>
  Friends
</h2>
<br>
<h2>
  Fun
</h2>